name: Discord Theme Request Notification

on:
  issues:
    types: [opened, labeled]

jobs:
  notify-discord:
    if: contains(github.event.issue.labels.*.name, 'theme-request')
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Extract theme type and priority from labels
          THEME_TYPE="Not specified"
          PRIORITY="Not specified"
          
          # Parse labels for theme type
          if echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "type:vencord"; then
            THEME_TYPE="Vencord"
          elif echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "type:betterdiscord"; then
            THEME_TYPE="BetterDiscord"
          elif echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "type:both"; then
            THEME_TYPE="Both"
          fi
          
          # Parse labels for priority
          if echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "priority:low"; then
            PRIORITY="🟢 Low"
          elif echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "priority:medium"; then
            PRIORITY="🟡 Medium"
          elif echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "priority:high"; then
            PRIORITY="🟠 High"
          elif echo "${{ join(github.event.issue.labels.*.name, ' ') }}" | grep -q "priority:urgent"; then
            PRIORITY="🔴 Urgent"
          fi
          
          # Get issue body preview (first 500 chars)
          BODY_PREVIEW=$(echo '${{ github.event.issue.body }}' | head -c 500)
          
          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"🎨 New Theme Request\",
                   \"description\": \"**${{ github.event.issue.title }}**\",
                   \"url\": \"${{ github.event.issue.html_url }}\",
                   \"color\": 3715860,
                   \"fields\": [
                     {
                       \"name\": \"👤 Submitted by\",
                       \"value\": \"[${{ github.event.issue.user.login }}](https://github.com/${{ github.event.issue.user.login }})\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"🎯 Theme Type\",
                       \"value\": \"${THEME_TYPE}\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"⚡ Priority\",
                       \"value\": \"${PRIORITY}\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"📋 Issue Number\",
                       \"value\": \"#${{ github.event.issue.number }}\",
                       \"inline\": true
                     }
                   ],
                   \"footer\": {
                     \"text\": \"Theme Requests Repository\"
                   },
                   \"timestamp\": \"${{ github.event.issue.created_at }}\"
                 }]
               }" \
               $DISCORD_WEBHOOK