name: Discord Theme Request Notification

on:
  issues:
    types: [opened, labeled]

jobs:
  notify-discord:
    if: contains(github.event.issue.labels.*.name, 'theme-request')
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          ISSUE_CREATED: ${{ github.event.issue.created_at }}
        run: |
          # Extract theme type and priority from labels
          THEME_TYPE="Not specified"
          PRIORITY="Not specified"
          
          LABELS="${{ join(github.event.issue.labels.*.name, ' ') }}"
          
          # Parse labels for theme type
          if echo "$LABELS" | grep -q "type:vencord"; then
            THEME_TYPE="Vencord"
          elif echo "$LABELS" | grep -q "type:betterdiscord"; then
            THEME_TYPE="BetterDiscord"
          elif echo "$LABELS" | grep -q "type:both"; then
            THEME_TYPE="Both"
          fi
          
          # Parse labels for priority
          if echo "$LABELS" | grep -q "priority:low"; then
            PRIORITY="🟢 Low"
          elif echo "$LABELS" | grep -q "priority:medium"; then
            PRIORITY="🟡 Medium"
          elif echo "$LABELS" | grep -q "priority:high"; then
            PRIORITY="🟠 High"
          elif echo "$LABELS" | grep -q "priority:urgent"; then
            PRIORITY="🔴 Urgent"
          fi
          
          # Create JSON payload
          cat << EOF > payload.json
          {
            "embeds": [{
              "title": "🎨 New Theme Request",
              "description": "**${ISSUE_TITLE}**",
              "url": "${ISSUE_URL}",
              "color": 3715860,
              "fields": [
                {
                  "name": "👤 Submitted by",
                  "value": "[${ISSUE_USER}](https://github.com/${ISSUE_USER})",
                  "inline": true
                },
                {
                  "name": "🎯 Theme Type",
                  "value": "${THEME_TYPE}",
                  "inline": true
                },
                {
                  "name": "⚡ Priority",
                  "value": "${PRIORITY}",
                  "inline": true
                },
                {
                  "name": "📋 Issue Number",
                  "value": "#${ISSUE_NUMBER}",
                  "inline": true
                }
              ],
              "footer": {
                "text": "Theme Requests Repository"
              },
              "timestamp": "${ISSUE_CREATED}"
            }]
          }
          EOF
          
          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d @payload.json \
               $DISCORD_WEBHOOK
